ARG FROM
ARG TAG

FROM ${FROM}:${TAG}

# Support for string substituion
SHELL ["/bin/bash", "-c"]

ARG LIBNVINFER

RUN apt-get update && apt-get install -y --no-install-recommends curl

RUN curl https://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1804/x86_64/libnvinfer${LIBNVINFER}.deb -o /tmp/libnvinfer.deb && \
  curl https://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1804/x86_64/libnvinfer-plugin${LIBNVINFER}.deb -o /tmp/libnvinfer-plugin.deb && \
  apt install -y --no-install-recommends /tmp/libnvinfer.deb /tmp/libnvinfer-plugin.deb

RUN apt-get update && apt-get install -y --no-install-recommends \
      libfreetype6-dev \
      libhdf5-serial-dev \
      libzmq3-dev \
      pkg-config \
    && apt-get autoremove -y curl \
    && apt-get autoclean \
    && rm -rf /var/lib/apt/lists/* /var/log/dpkg.log /var/cache/apt

# Link the libcuda stub to the location where some tools are searching for it
# Create configurations for dynamic linker and reconfigure it
RUN ln -s /usr/local/cuda/lib64/stubs/libcuda.so /usr/local/cuda/lib64/stubs/libcuda.so.1 \
    && echo "/usr/local/cuda/lib64/stubs" > /etc/ld.so.conf.d/z-cuda-stubs.conf \
    && echo "/usr/local/cuda/lib64" > /etc/ld.so.conf.d/cuda.conf \
    && echo "/usr/local/cuda/extras/CUPTI/lib64" > /etc/ld.so.conf.d/cupti.conf \
    && ldconfig

LABEL org.opencontainers.image.source https://github.com/ydataai/dockerfiles
