version: '3.8'

services:
  #### H2OFlow CPU Python Images
  ### Base CPU Python Image
  base_cpu_python:
     extends:
         file: ${CPU_BASE_IMAGES}
         service: base_cpu_python

  ### [PUSH] H2OFlow CPU Python Image
  h2oflow_cpu_python:
    image: ${PUBLIC_REGISTRY}h2oflow:${TAG}-cpu
    build:
      context: ../data-science/h2oflow/
      args:
         FROM: ${PUBLIC_REGISTRY}base_cpu_python
         TAG: ${TAG}
         RELEASE_NAME: ${RELEASE_NAME}
         H2O_RELEASE: ${H2O_RELEASE}
