version: '3.8'

services:
  #### VisualCode YData Torch 1.7 CPU Python Images
  ### Base CPU Python Image
  base_cpu_python:
     extends:
         file: ${CPU_BASE_IMAGES}
         service: base_cpu_python

  ### Base YData CPU Python Image
  base_ydata_cpu_python:
     extends:
         file: ${CPU_YDATA_PYTHON_BASE_IMAGES}
         service: base_ydata_cpu_python

  ## VisualCode YData CPU None Python Image
  visualcode_ydata_none_cpu_python:
     extends:
         file: ${CPU_VISUALCODE_PYTHON_NONE_IMAGES}
         service: visualcode_ydata_none_cpu_python

  ### VisualCode YData Torch 1.7 CPU Python Image
  visualcode_ydata_torch17_cpu_python:
    image: ${PUBLIC_REGISTRY}visualcode_torch-1.7:${TAG}-cpu
    build:
      context: ../data-science/torch-1.7/
      args:
         FROM: ${PUBLIC_REGISTRY}visualcode
         TAG: ${TAG}-cpu
         TYPE: cpu
