version: '3.8'

services:
  #### Jupyerlab YData Torch 1.7 CPU Python Images
  ### Base CPU Python Image
  base_cpu_python:
     extends:
         file: ${CPU_BASE_IMAGES}
         service: base_cpu_python

  ### Base YData CPU Python Image
  base_ydata_cpu_python:
     extends:
         file: ${CPU_YDATA_PYTHON_BASE_IMAGES}
         service: base_ydata_cpu_python

  ### JupyterLab YData CPU None Python Image
  base_jupyterlab_ydata_cpu_python:
     extends:
         file: ${CPU_JUPYTERLAB_PYTHON_NONE_IMAGES}
         service: jupyterlab_ydata_none_cpu_python

  ### [PUSH] [LAB] JupyterLab YData Torch 1.7 CPU Python Image
  jupyterlab_ydata_torch17_cpu_python:
    image: ${PUBLIC_REGISTRY}jupyterlab_python_torch-1.7:${TAG}-cpu
    build:
      context: ../data-science/torch-1.7/
      args:
         FROM: ${PUBLIC_REGISTRY}jupyterlab_python
         TAG: ${TAG}-cpu
         TYPE: cpu
