version: '3.8'

services:
  ##### Dask Workers
  #### Dask Worker 2021.6.0
  dask_worker_2021.06.0:
    image: ${PUBLIC_REGISTRY}dask-worker:${TAG}
    build:
      context: ../dask/2021.06.0/worker/
      args:
         FROM: daskdev/dask
         TAG: 2021.6.0


  ##### Dask Gateway
  #### Dask Gateway Ydata 2021.06.0
  dask_gateway_ydata_2021.06.0:
    image: ${PRIVATE_REGISTRY}dask-gateway-worker:${TAG}
    build:
      context: ../dask/2021.06.0/gateway/
      args:
         FROM: debian
         TAG: buster-slim
         DASK_VERSION: 2021.06.0
         DISTRIBUTED_VERSION: 2021.06.0
         CONDA_VERSION: py37_4.9.2
         CONDA_MD5: 3143b1116f2d466d9325c206b7de88f7
