version: '3.8'

services:
  #### Jupyerlab YData None Python Images
  ### Base CPU Python Image
  base_cpu_python:
     extends:
         file: ${CPU_BASE_IMAGES}
         service: base_cpu_python

  ### Base YData CPU Python Image
  base_ydata_cpu_python:
     extends:
         file: ${CPU_YDATA_PYTHON_BASE_IMAGES}
         service: base_ydata_cpu_python

  ### [PUSH] JupyterLab YData CPU None Python Image
  jupyterlab_ydata_none_cpu_python:
    image: ${PUBLIC_REGISTRY}jupyterlab_python:${TAG}-cpu
    build:
      context: ../data-science/jupyterlab_python/
      args:
         FROM: ${PUBLIC_REGISTRY}base_ydata_cpu_python
         TAG: ${TAG}
