version: '3.8'

services:
  #### Pipelines YData Torch 1.7 CPU Python Images
  ### Base CPU Python Image
  base_cpu_python:
     extends:
         file: docker-compose-base-images.yaml
         service: base_cpu_python

  ### Base YData CPU Python Image
  base_ydata_cpu_python:
     extends:
         file: docker-compose-ydata-base-images.yaml
         service: base_ydata_cpu_python

  ### Pipelines YData Torch 1.7 CPU Python Image
  pipelines_ydata_torch17_cpu_python:
    image: pipelines_ydata_torch17_cpu_python:${TAG}
    build:
      context: ../data-science/torch-1.7/
      args:
         FROM: base_ydata_cpu_python
         TAG: ${TAG}
         TYPE: CPU


  #### Pipelines YData Torch 1.7 GPU Python CUDA 10.1 Images
  ### Base GPU Python CUDA 10.1 Image
  base_gpu_python_cuda101:
     extends:
         file: docker-compose-base-images.yaml
         service: base_gpu_python_cuda101

  ### Base YData GPU Python CUDA 10.1 Image
  base_ydata_gpu_python_cuda101:
     extends:
         file: docker-compose-ydata-base-images.yaml
         service: base_ydata_gpu_python_cuda101

  ### Pipelines YData Torch 1.7 GPU Python CUDA 10.1 Image
  pipelines_ydata_torch17_gpu_python_cuda101:
    image: pipelines_ydata_torch17_gpu_python_cuda101:${TAG}
    build:
      context: ../data-science/torch-1.7/
      args:
         FROM: base_ydata_gpu_python_cuda101
         TAG: ${TAG}
         TYPE: GPU
