version: '3.8'

services:
  #### H2OFlow CPU Python Images
  ### Base CPU Python Image
  base_cpu_python:
     extends:
         file: docker-compose-base-images.yaml
         service: base_cpu_python

  ### H2OFlow CPU Python Image
  h2oflow_cpu_python:
    image: h2oflow:${TAG}-cpu
    build:
      context: ../data-science/h2oflow/
      args:
         FROM: base_cpu_python
         TAG: ${TAG}
         RELEASE_NAME: ${RELEASE_NAME}
         H2O_RELEASE: ${H2O_RELEASE}


  #### H2OFlow GPU Python Images
  ### Base GPU Python CUDA 10.0 Image
  base_gpu_python_cuda100:
     extends:
         file: docker-compose-base-images.yaml
         service: base_gpu_python_cuda100

  ### H2OFlow GPU Python CUDA 10.0 Image
  h2oflow_gpu_python_cuda100:
    image: h2oflow:${TAG}-gpu
    build:
      context: ../data-science/h2oflow/
      args:
         FROM: base_gpu_python_cuda100
         TAG: ${TAG}
         RELEASE_NAME: ${RELEASE_NAME}
         H2O_RELEASE: ${H2O_RELEASE}
