version: '3.8'

services:
  #### Pipelines YData CPU Python Images
  ### Base CPU Python Image
  base_cpu_python:
     extends:
         file: docker-compose-base-images.yaml
         service: base_cpu_python

  ### Base YData CPU Python Image
  base_ydata_cpu_python:
     extends:
         file: docker-compose-ydata-base-images.yaml
         service: base_ydata_cpu_python

  ### Pipelines YData CPU Python Image
  pipelines_ydata_cpu_python:
    image: pipelines_ydata_cpu_python:${TAG}
    build:
      context: ../data-science/ydata/
      args:
         FROM: base_ydata_cpu_python
         TAG: ${TAG}


  #### Pipelines YData GPU Python Images
  ### Base GPU Python CUDA 11.0 Image
  base_gpu_python_cuda110:
     extends:
         file: docker-compose-base-images.yaml
         service: base_gpu_python_cuda110

  ### Base YData GPU Python CUDA 11.0 Image
  base_ydata_gpu_python_cuda110:
     extends:
         file: docker-compose-jupyerlab-base-images.yaml
         service: base_ydata_gpu_python_cuda110

  ### Pipelines YData GPU Python CUDA 11.0 Image
  pipelines_ydata_gpu_python_cuda110:
    image: pipelines_ydata_gpu_python_cuda110:${TAG}
    build:
      context: ../data-science/ydata/
      args:
         FROM: base_ydata_gpu_python_cuda110
         TAG: ${TAG}
