version: '3.8'

services:
  #### Jupyerlab YData Torch 1.7 CPU Python Images
  ### Base CPU Python Image
  base_cpu_python:
     extends:
         file: docker-compose-base-images.yaml
         service: base_cpu_python

  ### Base YData CPU Python Image
  base_ydata_cpu_python:
     extends:
         file: docker-compose-ydata-base-images.yaml
         service: base_ydata_cpu_python

  ### Base JupyterLab YData CPU Python Image
  base_jupyterlab_ydata_cpu_python:
     extends:
         file: docker-compose-jupyerlab-base-images.yaml
         service: base_jupyterlab_ydata_cpu_python

  ### JupyterLab YData Torch 1.7 CPU Python Image
  jupyterlab_ydata_torch17_cpu_python:
    image: jupyterlab_ydata_torch17_cpu_python:${TAG}
    build:
      context: ../data-science/torch-1.7/
      args:
         FROM: base_jupyterlab_ydata_cpu_python
         TAG: ${TAG}
         TYPE: CPU


  #### Jupyerlab YData Torch 1.7 GPU Python CUDA 10.1 Images
  ### Base GPU Python CUDA 10.1 Image
  base_gpu_python_cuda101:
     extends:
         file: docker-compose-base-images.yaml
         service: base_gpu_python_cuda101

  ### Base YData GPU Python CUDA 10.1 Image
  base_ydata_gpu_python_cuda101:
     extends:
         file: docker-compose-ydata-base-images.yaml
         service: base_ydata_gpu_python_cuda101

  ### Base JupyterLab YData GPU Python CUDA 10.1 Image
  base_jupyterlab_ydata_gpu_python_cuda101:
     extends:
         file: docker-compose-jupyerlab-base-images.yaml
         service: base_jupyterlab_ydata_gpu_python_cuda101

  ### JupyterLab YData Torch 1.7 GPU Python CUDA 10.1 Image
  jupyterlab_ydata_torch17_gpu_python_cuda101:
    image: jupyterlab_ydata_torch17_gpu_python_cuda101:${TAG}
    build:
      context: ../data-science/torch-1.7/
      args:
         FROM: base_jupyterlab_ydata_gpu_python_cuda101
         TAG: ${TAG}
         TYPE: GPU
