version: '3.8'

services:
  ##### Tensorflow 1.15
  #### Jupyerlab Tensorflow 1.15 GPU R CUDA 10.0 Images
  ### Base GPU R CUDA 10.0 Image
  base_gpu_r_cuda100:
     extends:
         file: ${GPU_BASE_IMAGES}
         service: base_gpu_r_cuda100

  ## JupyterLab GPU None R CUDA 10.0 Image
  jupyterlab_none_gpu_r_cuda100:
     extends:
         file: ${GPU_JUPYTERLAB_R_NONE_IMAGES}
         service: jupyterlab_none_gpu_r_cuda100

  ### Base JupyterLab Tensorflow 1.15 GPU R CUDA 10.0 Image
  base_jupyterlab_tensorflow115_gpu_r_cuda100:
    image: base_jupyterlab_tensorflow115_gpu_r_cuda100:${TAG}
    build:
      context: ../data-science/tensorflow/
      args:
         FROM: ${PUBLIC_REGISTRY}jupyterlab_r
         TAG: ${TAG}-gpu-cuda10.0
         TYPE: gpu
         VERSION: 1.15

  ### [PUSH] [LAB] JupyterLab Tensorflow 1.15 GPU R CUDA 10.0 Image
  jupyterlab_tensorflow115_gpu_r:
    image: ${PUBLIC_REGISTRY}jupyterlab_r_tensorflow-1.15:${TAG}-gpu
    build:
      context: ../data-science/jupyterlab_r_tensorflow/
      args:
         FROM: base_jupyterlab_tensorflow115_gpu_r_cuda100
         TAG: ${TAG}
         TYPE: gpu
         VERSION: 1.15



  ##### Tensorflow 2.3
  #### Jupyerlab Tensorflow 2.3 GPU R CUDA 10.1 Images
  ### Base GPU R CUDA 10.1 Image
  base_gpu_r_cuda101:
     extends:
         file: ${GPU_BASE_IMAGES}
         service: base_gpu_r_cuda101

  ## JupyterLab GPU None R CUDA 10.1 Image
  jupyterlab_none_gpu_r_cuda101:
     extends:
         file: ${GPU_JUPYTERLAB_R_NONE_IMAGES}
         service: jupyterlab_none_gpu_r_cuda101

  ### Base JupyterLab Tensorflow 2.3 GPU R CUDA 10.1 Image
  base_jupyterlab_tensorflow23_gpu_r_cuda101:
    image: base_jupyterlab_tensorflow23_gpu_r_cuda101:${TAG}
    build:
      context: ../data-science/tensorflow/
      args:
         FROM: ${PUBLIC_REGISTRY}jupyterlab_r
         TAG: ${TAG}-gpu-cuda10.1
         TYPE: gpu
         VERSION: 2.3

  ### [PUSH] [LAB] JupyterLab Tensorflow 2.3 GPU R CUDA 10.1 Image
  jupyterlab_tensorflow23_gpu_r:
    image: ${PUBLIC_REGISTRY}jupyterlab_r_tensorflow-2.3:${TAG}-gpu
    build:
      context: ../data-science/jupyterlab_r_tensorflow/
      args:
         FROM: base_jupyterlab_tensorflow23_gpu_r_cuda101
         TAG: ${TAG}
         TYPE: gpu
         VERSION: 2.3
