version: '3.8'

services:
  #### Jupyerlab YData GPU Python Images
  ### Base GPU Python CUDA 11.0 Image
  base_gpu_python_cuda110:
     extends:
         file: ${GPU_BASE_IMAGES}
         service: base_gpu_python_cuda110

  ### Base YData GPU Python CUDA 11.0 Image
  base_ydata_gpu_python_cuda110:
     extends:
         file: ${GPU_YDATA_PYTHON_BASE_IMAGES}
         service: base_ydata_gpu_python_cuda110

  ### JupyterLab YData GPU None Python CUDA 11.0 Image
  jupyterlab_ydata_none_gpu_python_cuda110:
     extends:
         file: ${GPU_JUPYTERLAB_PYTHON_NONE_IMAGES}
         service: jupyterlab_ydata_none_gpu_python_cuda110

  ### JupyterLab YData GPU Python CUDA 11.0 Image
  jupyterlab_ydata_gpu_python_cuda110:
    image: jupyterlab_ydata_gpu_python_cuda110:${TAG}
    build:
      context: ../data-science/ydata/
      args:
         FROM: ${PUBLIC_REGISTRY}jupyterlab_python
         TAG: ${TAG}-gpu-cuda11.0

  ### [PUSH] JupyterLab YData GPU Python CUDA 11.0 Image - NOPIP
  jupyterlab_ydata_gpu_python_cuda110_nopip:
    image: ${PRIVATE_REGISTRY}ydata:${TAG}-gpu
    build:
      context: ../data-science/ydata-nopip/
      args:
         FROM: jupyterlab_ydata_gpu_python_cuda110
         TAG: ${TAG}
