version: '3.8'

services:
  #### VisualCode GPU Python Images
  ### CUDA 10.0
  ## Base GPU Python CUDA 10.0 Image
  base_gpu_python_cuda100:
     extends:
         file: ${GPU_BASE_IMAGES}
         service: base_gpu_python_cuda100

  ## Base YData GPU Python CUDA 10.0 Image
  base_ydata_gpu_python_cuda100:
    extends:
      file: ${GPU_YDATA_PYTHON_BASE_IMAGES}
      service: base_ydata_gpu_python_cuda100

  ## [PUSH] VisualCode YData GPU None Python CUDA 10.0 Image
  visualcode_ydata_none_gpu_python_cuda100:
    image: ${PUBLIC_REGISTRY}visualcode:${TAG}-gpu-cuda10.0
    build:
      context: ../data-science/visualcode_python/
      args:
         FROM: ${PUBLIC_REGISTRY}base_ydata_gpu_python_cuda100
         TAG: ${TAG}


  ### CUDA 10.1
  ## Base GPU Python CUDA 10.1 Image
  base_gpu_python_cuda101:
     extends:
         file: ${GPU_BASE_IMAGES}
         service: base_gpu_python_cuda101

  ## Base YData GPU Python CUDA 10.1 Image
  base_ydata_gpu_python_cuda101:
    extends:
      file: ${GPU_YDATA_PYTHON_BASE_IMAGES}
      service: base_ydata_gpu_python_cuda101

  ## [PUSH] VisualCode YData GPU None Python CUDA 10.1 Image
  visualcode_ydata_none_gpu_python_cuda101:
    image: ${PUBLIC_REGISTRY}visualcode:${TAG}-gpu-cuda10.1
    build:
      context: ../data-science/visualcode_python/
      args:
         FROM: ${PUBLIC_REGISTRY}base_ydata_gpu_python_cuda101
         TAG: ${TAG}

  ### CUDA 11.0
  ## Base GPU Python CUDA 11.0 Image
  base_gpu_python_cuda110:
     extends:
         file: ${GPU_BASE_IMAGES}
         service: base_gpu_python_cuda110

  ## Base YData GPU Python CUDA 11.0 Image
  base_ydata_gpu_python_cuda110:
    extends:
      file: ${GPU_YDATA_PYTHON_BASE_IMAGES}
      service: base_ydata_gpu_python_cuda110

  ## [PUSH] VisualCode YData GPU None Python CUDA 11.0 Image
  visualcode_ydata_none_gpu_python_cuda110:
    image: ${PUBLIC_REGISTRY}visualcode:${TAG}-gpu-cuda11.0
    build:
      context: ../data-science/visualcode_python/
      args:
         FROM: ${PUBLIC_REGISTRY}base_ydata_gpu_python_cuda110
         TAG: ${TAG}
