version: '3.8'

services:
  #### JupyterLab GPU Python Images
  ### CUDA 10.0
  ## Base GPU Python CUDA 10.0 Image
  base_gpu_python_cuda100:
     extends:
         file: ${GPU_BASE_IMAGES}
         service: base_gpu_python_cuda100

  ## [PUSH] Base YData GPU Python CUDA 10.0 Image
  base_ydata_gpu_python_cuda100:
    image: ${PUBLIC_REGISTRY}base_ydata_gpu_python_cuda100:${TAG}
    build:
      context: ../data-science/python_ydata_base/
      args:
         FROM: ${PUBLIC_REGISTRY}base_gpu_python_cuda100
         TAG: ${TAG}


  ### CUDA 10.1
  ## Base GPU Python CUDA 10.1 Image
  base_gpu_python_cuda101:
     extends:
         file: ${GPU_BASE_IMAGES}
         service: base_gpu_python_cuda101

  ## [PUSH] Base YData GPU Python CUDA 10.1 Image
  base_ydata_gpu_python_cuda101:
    image: ${PUBLIC_REGISTRY}base_ydata_gpu_python_cuda101:${TAG}
    build:
      context: ../data-science/python_ydata_base/
      args:
         FROM: ${PUBLIC_REGISTRY}base_gpu_python_cuda101
         TAG: ${TAG}


  ### CUDA 11.0
  ## Base GPU Python CUDA 11.0 Image
  base_gpu_python_cuda110:
     extends:
         file: ${GPU_BASE_IMAGES}
         service: base_gpu_python_cuda110

  ## [PUSH] Base YData GPU Python CUDA 11.0 Image
  base_ydata_gpu_python_cuda110:
    image: ${PUBLIC_REGISTRY}base_ydata_gpu_python_cuda110:${TAG}
    build:
      context: ../data-science/python_ydata_base/
      args:
         FROM: ${PUBLIC_REGISTRY}base_gpu_python_cuda110
         TAG: ${TAG}
