version: '3.8'

services:
  ##### Tensorflow 1.15
  #### Pipelines YData Tensorflow 1.15 GPU Python CUDA 10.0 Images
  ### Base GPU Python CUDA 10.0 Image
  base_gpu_python_cuda100:
     extends:
         file: ${GPU_BASE_IMAGES}
         service: base_gpu_python_cuda100

  ### Base YData GPU Python CUDA 10.0 Image
  base_ydata_gpu_python_cuda100:
     extends:
         file: ${GPU_YDATA_PYTHON_BASE_IMAGES}
         service: base_ydata_gpu_python_cuda100

  ### [PUSH] Pipelines YData Tensorflow 1.15 GPU Python CUDA 10.0 Image
  pipelines_ydata_tensorflow115_gpu_python_cuda100:
    image: ${PUBLIC_REGISTRY}pipelines_python_tensorflow-1.15:${TAG}-gpu
    build:
      context: ../data-science/tensorflow/
      args:
         FROM: ${PUBLIC_REGISTRY}base_ydata_gpu_python_cuda100
         TAG: ${TAG}
         TYPE: gpu
         VERSION: 1.15



  ##### Tensorflow 2.3
  #### Pipelines YData Tensorflow 2.3 GPU Python CUDA 10.1 Images
  ### Base GPU Python CUDA 10.1 Image
  base_gpu_python_cuda101:
     extends:
         file: ${GPU_BASE_IMAGES}
         service: base_gpu_python_cuda101

  ### Base YData GPU Python CUDA 10.1 Image
  base_ydata_gpu_python_cuda101:
     extends:
         file: ${GPU_YDATA_PYTHON_BASE_IMAGES}
         service: base_ydata_gpu_python_cuda101

  ### [PUSH] Pipelines YData Tensorflow 2.3 GPU Python CUDA 10.1 Image
  pipelines_ydata_tensorflow23_gpu_python_cuda101:
    image: ${PUBLIC_REGISTRY}pipelines_python_tensorflow-2.3:${TAG}-gpu
    build:
      context: ../data-science/tensorflow/
      args:
         FROM: ${PUBLIC_REGISTRY}base_ydata_gpu_python_cuda101
         TAG: ${TAG}
         TYPE: gpu
         VERSION: 2.3
