version: '3.8'

services:
  #### H2OFlow GPU Python Images
  ### Base GPU Python CUDA 10.0 Image
  base_gpu_python_cuda100:
     extends:
         file: ${GPU_BASE_IMAGES}
         service: base_gpu_python_cuda100

  ### [PUSH] [LAB] H2OFlow GPU Python CUDA 10.0 Image
  h2oflow_gpu_python_cuda100:
    image: ${PUBLIC_REGISTRY}h2oflow:${TAG}-gpu
    build:
      context: ../data-science/h2oflow/
      args:
         FROM: ${PUBLIC_REGISTRY}base_gpu_python_cuda100
         TAG: ${TAG}
         RELEASE_NAME: ${RELEASE_NAME}
         H2O_RELEASE: ${H2O_RELEASE}
