ARG TAG
ARG JUPYTERLAB_VERSION

FROM ydata/jupyterlab_r:${TAG}

LABEL JupyterLabVersion=1.2.15

ARG TYPE

RUN Rscript -e "install.packages(c('torch, torchvision'), repos = 'http://cran.us.r-project.org')"
RUN Rscript -e "torch::install_torch(version = '1.7.1', type = 'cpu', reinstall = FALSE)"

LABEL org.opencontainers.image.source https://github.com/ydataai/dockerfiles

