name: Prereleased

on:
  release:
    types: [ prereleased ]

jobs:
  prepare:
    name: Prepare
    runs-on: ubuntu-20.04

    outputs:
      version: ${{ steps.version.outputs.value }}

    steps:
    - name: Version
      id: version
      run: echo ::set-output name=value::`echo ${{ github.ref }} | sed -n -E 's/refs\/tags\/([0-9]+.[0-9]+.[0-9]+)/\1/p'`

  build-base-images:
    name: Build and push Laboratories Base Docker images
    runs-on: ubuntu-20.04

    needs: prepare

    steps:
    - uses: actions/checkout@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Build and Push Lab Base images
      run: ./images-builder.sh base ${{ needs.prepare.outputs.version }}

  build-jupyterlab-images:
    name: Build and push JupyterLab and bundles Docker images
    runs-on: ubuntu-20.04

    needs: [prepare, build-base-images]

    steps:
    - uses: actions/checkout@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Build and Push JupyterLab images
      run: ./images-builder.sh jupyterlab ${{ needs.prepare.outputs.version }}

  build-h2o-images:
    name: Build and push H2O Docker images
    runs-on: ubuntu-20.04

    needs: [prepare, build-base-images, build-jupyterlab-images]

    steps:
    - uses: actions/checkout@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Build and Push H2O images
      run: ./images-builder.sh h2o ${{ needs.prepare.outputs.version }}

  build-ydata-image:
    name: Build and push YData Docker images
    runs-on: ubuntu-20.04

    needs: [prepare, build-base-images, build-jupyterlab-images]

    steps:
    - uses: actions/checkout@v2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ${{ secrets.PRIVATE_CONTAINER_REGISTRY }}
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GHCR_TOKEN }}

    - name: Build and Push YData image
      run: ./images-builder.sh ydata ${{ needs.prepare.outputs.version }}
